apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 192.168.153.132/my-app:2
        ports:
        - containerPort: 8080